[env:esp32-p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-p4
framework = arduino

board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.psram_type = opi
board_build.f_cpu = 400000000L

upload_protocol = esptool
upload_port = /dev/cu.usbmodem1452401

monitor_speed = 115200
upload_speed = 460800

build_flags =
    -I include
    -I .
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0
    -DUSB_MANUFACTURER="\"iMakie-P4\""
    -DUSB_PRODUCT="\"iMakie-P4-Master\""
    -DCORE_DEBUG_LEVEL=3
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_USE_DRAW_SW_ASM=LV_DRAW_SW_ASM_NONE
    -DLV_USE_DRAW_SW_ASM_HELIUM=0
    -DLV_USE_DRAW_SW_ASM_NEON=0
    -Wno-deprecated-declarations
    -Wno-attributes


lib_deps =
    lvgl/lvgl@^9.5.0
