[env:lolin_s2_mini_ota]
platform = espressif32
board = lolin_s2_mini
framework = arduino
 
upload_protocol = espota
upload_port     = 192.168.1.15
upload_flags    =
    --auth=9821

monitor_port    = /dev/cu.usbmodem01
monitor_speed   = 115200
 
board_build.arduino.memory_type = qio_qspi
board_build.partitions = partitions_4MB_ota.csv
 
build_flags =
    -I src
    -D CONFIG_TINYUSB_CDC_ENABLED=1
    -DCONFIG_ESP32_RMT_MEM_BLOCKS=4
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -Wno-cpp
    -Wno-deprecated-declarations
    -Wno-attributes
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    makuna/NeoPixelBus@^2.8.4
    lovyan03/LovyanGFX@^1.2.19
    lennarthennigs/Button2@^2.5.0
    tzapu/WiFiManager @ ^2.0.17