[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino

upload_protocol = esptool
upload_port     = /dev/cu.usbmodem01
monitor_speed   = 115200

board_build.arduino.memory_type = qio_qspi   ; S2FN4R2 usa QSPI PSRAM

build_flags = 
    -D CONFIG_TINYUSB_CDC_ENABLED=1
    -DCONFIG_ESP32_RMT_MEM_BLOCKS=4
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue   ; solo S2/S3, evita bugs de cache
    -DCORE_DEBUG_LEVEL=3


lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.3
    lovyan03/LovyanGFX@^1.2.19
    lennarthennigs/Button2@^2.3.2
    madhephaestus/ESP32Encoder@^0.11.0